# Generated by Django 4.2.2 on 2023-06-20 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="story",
            old_name="catergories",
            new_name="categories",
        ),
        migrations.RenameField(
            model_name="story",
            old_name="taggit",
            new_name="tag",
        ),
    ]
