# Generated by Django 4.2.2 on 2023-06-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0002_alter_chapter_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={},
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
